------- Alter de las tablas -------

CREATE PROCEDURE AlterTables
AS
BEGIN
    SET NOCOUNT ON;

	  -- Desactivar restricciones y desencadenadores en la tabla
ALTER TABLE STG_FACT_VENTAS NOCHECK CONSTRAINT ALL;
DISABLE TRIGGER ALL ON STG_FACT_VENTAS;

ALTER TABLE STG_FACT_VENTAS
ALTER COLUMN CANTIDAD_VENDIDA INT;

ALTER TABLE STG_FACT_VENTAS
ALTER COLUMN CANTIDAD_VENDIDA decimal(18,2);


UPDATE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS]
SET Monto_Vendido = REPLACE(Monto_Vendido, '.','')
WHERE Monto_Vendido LIKE '%.%'

-- Cambiar el tipo de dato de la columna [Monto_Vendido] a decimal(18,2)
ALTER TABLE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS] ALTER COLUMN [Monto_Vendido] DECIMAL(18,2);

UPDATE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS]
SET Precio = REPLACE(Precio, ',','.')
WHERE Precio LIKE '%,%'

ALTER TABLE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS] ALTER COLUMN [Precio] DECIMAL(18,5);

UPDATE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS]
SET Comision_Comercial = REPLACE(Comision_Comercial, '.',',')
WHERE Comision_Comercial LIKE '%.%'

UPDATE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS]
SET Comision_Comercial = REPLACE(Comision_Comercial, ',','')
WHERE Comision_Comercial LIKE '%,%'

-- Activar restricciones y desencadenadores en la tabla
ALTER TABLE [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS] CHECK CONSTRAINT ALL;
ENABLE TRIGGER ALL ON [DW_COMERCIAL].[dbo].[STG_FACT_VENTAS];

ALTER TABLE [DW_COMERCIAL].[dbo].FACT_VENTAS ALTER COLUMN Comision_Comercial  DECIMAL(18,2);

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_CATEGORIA]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_CLIENTE]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_PAIS]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_PRODUCTO]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_SUCURSAL]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[DIM_TIEMPO]
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].DIM_VENDEDOR
DROP COLUMN [FECHA_ALTA],[FECHA_UPDATE],[USUARIO_ALTA],[USUARIO_UPDATE] ;

ALTER TABLE [DW_COMERCIAL].[dbo].[FACT_VENTAS]
DROP COLUMN [FECHA_ALTA],USUARIO_ALTA;

END


EXECUTE AlterTables 


